version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - modernize
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      min-occurrences: 7
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
    modernize:
      disable:
        - omitzero
        - newexpr
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - goconst
        path: _test\.go$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
