apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kryptlet.fullname" . }}-blobs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kryptlet.labels" . | nindent 4 }}
binaryData:
  {{- if .Values.blobs }}
  {{- toYaml .Values.blobs | nindent 2 }}
  {{- end }}
